config/routes.rb
Proy::Application.routes.draw do

  get "home/index"
  root :to => 'home#index'
  devise_for :users

  resources :clientes

  resources :feriados

  root :to => 'home#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :user
  attr_accessible :apellido, :email, :empresa, :ingreso, :nombre
end

app/models/feriado.rb
class Feriado < ActiveRecord::Base
  attr_accessible :description, :fecha
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :feriados
  has_many :clients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :new_usuario

  def new_usuario
  	@user = User.new
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/feriados_controller.rb
class FeriadosController < ApplicationController
  # GET /feriados
  # GET /feriados.json
  
  def index
    @feriados = Feriado.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feriados }
    end
  end

  # GET /feriados/1
  # GET /feriados/1.json
  def show
    @feriado = Feriado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feriado }
    end
  end

  # GET /feriados/new
  # GET /feriados/new.json
  def new
    @feriado = Feriado.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feriado }
    end
  end

  # GET /feriados/1/edit
  def edit
    @feriado = Feriado.find(params[:id])
  end

  # POST /feriados
  # POST /feriados.json
  def create
    @feriado = Feriado.new(params[:feriado])

    respond_to do |format|
      if @feriado.save
        format.html { redirect_to @feriado, notice: 'Feriado was successfully created.' }
        format.json { render json: @feriado, status: :created, location: @feriado }
      else
        format.html { render action: "new" }
        format.json { render json: @feriado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feriados/1
  # PUT /feriados/1.json
  def update
    @feriado = Feriado.find(params[:id])

    respond_to do |format|
      if @feriado.update_attributes(params[:feriado])
        format.html { redirect_to @feriado, notice: 'Feriado was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feriado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feriados/1
  # DELETE /feriados/1.json
  def destroy
    @feriado = Feriado.find(params[:id])
    @feriado.destroy

    respond_to do |format|
      format.html { redirect_to feriados_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/feriados_helper.rb
module FeriadosHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :apellido %><br />
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :empresa %><br />
    <%= f.text_field :empresa %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :ingreso %><br />
    <%= f.date_select :ingreso %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Lista de clientes</h1>

<table>
  <tr>
    <th>Apellido</th>
    <th>Nombre</th>
    <th>Empresa</th>
    <th>Email</th>
    <th>Ingreso</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.apellido %></td>
    <td><%= cliente.nombre %></td>
    <td><%= cliente.empresa %></td>
    <td><%= cliente.email %></td>
    <td><%= cliente.ingreso %></td>
    <td><%= link_to 'Ver', cliente %></td>
    <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Apellido:</b>
  <%= @cliente.apellido %>
</p>

<p>
  <b>Nombre:</b>
  <%= @cliente.nombre %>
</p>

<p>
  <b>Empresa:</b>
  <%= @cliente.empresa %>
</p>

<p>
  <b>Email:</b>
  <%= @cliente.email %>
</p>

<p>
  <b>Ingreso:</b>
  <%= @cliente.ingreso %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/feriados/_form.html.erb
<%= form_for(@feriado) do |f| %>
  <% if @feriado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feriado.errors.count, "error") %> prohibited this feriado from being saved:</h2>

      <ul>
      <% @feriado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.date_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feriados/edit.html.erb
<h1>Editing feriado</h1>

<%= render 'form' %>

<%= link_to 'Ver', @feriado %> |
<%= link_to 'Back', feriados_path %>

app/views/feriados/index.html.erb
<h1>Lista de feriados</h1>

<table>
  <tr>
    <th>Descripcion</th>
    <th>Fecha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feriados.each do |feriado| %>
  <tr>
    <td><%= feriado.description %></td>
    <td><%= feriado.fecha %></td>
    <td><%= link_to 'Ver', feriado %></td>
    <td><%= link_to 'Editar', edit_feriado_path(feriado) %></td>
    <td><%= link_to 'Eliminar', feriado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Agregar Nuevo Feriado', new_feriado_path %>

app/views/feriados/new.html.erb
<h1>Nuevo feriado</h1>

<%= render 'form' %>

<%= link_to 'Back', feriados_path %>

app/views/feriados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descripcion:</b>
  <%= @feriado.description %>
</p>

<p>
  <b>Fecha:</b>
  <%= @feriado.fecha %>
</p>


<%= link_to 'Editar', edit_feriado_path(@feriado) %> |
<%= link_to 'Back', feriados_path %>

app/views/home/index.html.erb
      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Notifier holidays</h1>
        <p>Es una aplicacion quele permitira notificar a sus clientes mediante un mail los dias feriados , asi esten al tanto de los dias que usted no trabaja</p>
        <p><a class="btn btn-primary btn-large" href="http://localhost:3000/users/sign_in#">Adquirir ahora »</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Notificación Automática</h2>
          <p>Automatize la notificación de sus días no laborables. Fácil interfáz configurable. Cargue sus datos personales, lista de clientes y calendario de feriados y despreocúpese de olvidar notificar un feriado a sus clientes.</p>
          <p><a class="btn" href="http://twitter.github.com/bootstrap/examples/hero.html#">Ver Detalles »</a></p>
        </div>
        <div class="span4">
          <h2>Envío Masivo de Emails</h2>
          <p>Hasta 200 emails por dia con cuenta free. Consulte planes especiales.</p>
          <p><a class="btn" href="http://twitter.github.com/bootstrap/examples/hero.html#">Ver Detalles »</a></p>
       </div>
        <div class="span4">
          <h2>Emails personalizados</h2>
          <p>Flexible para generar marcado y cargar templates a su medida.</p>
          <p><a class="btn" href="http://twitter.github.com/bootstrap/examples/hero.html#">Ver Detalles »</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>© by fl </p>
      </footer>


  

app/views/layouts/1application.html.erb
<!DOCTYPE html>
<!-- saved from url=(0054)http://twitter.github.com/bootstrap/examples/hero.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Holidays</title>
  <%= stylesheet_link_tag    "bootstrap", "bootstrap.min","bootstrap-responsive","bootstrap-responsive.min", :media => "all" %>
  <%= javascript_include_tag "bootstrap", "bootstrap.min", "application" %>
  <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="http://twitter.github.com/bootstrap/assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Notifica tus feriados", root_path, :class => :brand %>
          <% if user_signed_in? %>
              <div class="nav-collapse collapse">
                <ul class="nav">


                  <li><%= link_to "Mis Feriados", feriados_path %></li>
                  <li><%= link_to("Cerrar Sesión", destroy_user_session_path, :method =>:delete) %></li>
                  <li class="dropdown">
                    <a href="http://twitter.github.com/bootstrap/examples/hero.html#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="http://twitter.github.com/bootstrap/examples/hero.html#">Action</a></li>
                      <li><a href="http://twitter.github.com/bootstrap/examples/hero.html#">Another action</a></li>
                      <li><a href="http://twitter.github.com/bootstrap/examples/hero.html#">Something else here</a></li>
                      <li class="divider"></li>
                      <li class="nav-header">Nav header</li>
                      <li><a href="http://twitter.github.com/bootstrap/examples/hero.html#">Separated link</a></li>
                      <li><a href="http://twitter.github.com/bootstrap/examples/hero.html#">One more separated link</a></li>
                    </ul>
                  </li>
                </ul>


                <%= form_for @user, :url => user_session do |f| %>
                  
                  <%= f.email_field :user, :address %>
                  <%= f.label, :email %> 
                  
                  <%= f.password_field :password %>
                  <%= f.label , :password%>

                <%end %>


                <form class="navbar-form pull-right">
                  <input class="span2" type="text" placeholder="Email">
                  <input class="span2" type="password" placeholder="Password">
                  <button type="submit" class="btn">Sign in</button>
                </form>
              </div><!--/.nav-collapse -->
          <%end%>    
        </div>
      </div>
    </div>
    <div class="container">
      <div class="notice"><%= notice %></div>
      <div class="alert"><%= alert %></div>
    
  	<%= yield %>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="./Bootstrap, from Twitter_files/jquery.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-transition.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-alert.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-modal.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-dropdown.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-scrollspy.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-tab.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-tooltip.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-popover.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-button.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-collapse.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-carousel.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-typeahead.js"></script>

</body></html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>